// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.cooldemo.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class UserInfo (
  val userId: String,
  val nickname: String? = null,
  val avatarUrl: String? = null,
  val email: String? = null,
  val phone: String? = null,
  val vipLevel: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserInfo {
      val userId = pigeonVar_list[0] as String
      val nickname = pigeonVar_list[1] as String?
      val avatarUrl = pigeonVar_list[2] as String?
      val email = pigeonVar_list[3] as String?
      val phone = pigeonVar_list[4] as String?
      val vipLevel = pigeonVar_list[5] as Long?
      return UserInfo(userId, nickname, avatarUrl, email, phone, vipLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      userId,
      nickname,
      avatarUrl,
      email,
      phone,
      vipLevel,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SettingItem (
  val key: String,
  val value: String? = null,
  val label: String? = null,
  val type: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SettingItem {
      val key = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String?
      val label = pigeonVar_list[2] as String?
      val type = pigeonVar_list[3] as String?
      return SettingItem(key, value, label, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      value,
      label,
      type,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeviceInfo (
  val platform: String,
  val osVersion: String,
  val deviceModel: String,
  val appVersion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfo {
      val platform = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val deviceModel = pigeonVar_list[2] as String
      val appVersion = pigeonVar_list[3] as String
      return DeviceInfo(platform, osVersion, deviceModel, appVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      deviceModel,
      appVersion,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApiResponse (
  val success: Boolean,
  val data: String? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApiResponse {
      val success = pigeonVar_list[0] as Boolean
      val data = pigeonVar_list[1] as String?
      val errorCode = pigeonVar_list[2] as String?
      val errorMessage = pigeonVar_list[3] as String?
      return ApiResponse(success, data, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      data,
      errorCode,
      errorMessage,
    )
  }
}
private open class ApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SettingItem.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApiResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is UserInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SettingItem -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DeviceInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApiResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UserApi {
  fun getCurrentUser(callback: (Result<ApiResponse>) -> Unit)
  fun isLoggedIn(callback: (Result<ApiResponse>) -> Unit)
  fun updateUserInfo(userInfo: UserInfo, callback: (Result<ApiResponse>) -> Unit)
  fun logout(callback: (Result<ApiResponse>) -> Unit)

  companion object {
    /** The codec used by UserApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
    /** Sets up an instance of `UserApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UserApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.UserApi.getCurrentUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCurrentUser{ result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.UserApi.isLoggedIn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isLoggedIn{ result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.UserApi.updateUserInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userInfoArg = args[0] as UserInfo
            api.updateUserInfo(userInfoArg) { result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.UserApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout{ result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SettingApi {
  fun getAllSettings(callback: (Result<ApiResponse>) -> Unit)
  fun getSetting(key: String, callback: (Result<ApiResponse>) -> Unit)
  fun updateSetting(key: String, value: String?, callback: (Result<ApiResponse>) -> Unit)
  fun getDeviceInfo(callback: (Result<ApiResponse>) -> Unit)

  companion object {
    /** The codec used by SettingApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
    /** Sets up an instance of `SettingApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SettingApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.SettingApi.getAllSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAllSettings{ result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.SettingApi.getSetting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.getSetting(keyArg) { result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.SettingApi.updateSetting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String?
            api.updateSetting(keyArg, valueArg) { result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.module_flutter.SettingApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceInfo{ result: Result<ApiResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class EventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EventApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
  }
  fun onUserInfoChanged(userInfoArg: UserInfo?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.module_flutter.EventApi.onUserInfoChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(userInfoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSettingChanged(keyArg: String, valueArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.module_flutter.EventApi.onSettingChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(keyArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAppLifecycleChanged(stateArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.module_flutter.EventApi.onAppLifecycleChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
